### PR TITLE
Tweak travis build

### PR DESCRIPTION
**Pull request by maxime-rainville**
Fixing broken build introduce in https://github.com/jonom/silverstripe-focuspoint/pull/78

### CODE REVIEW

**Comment by jonom** [comment]
FYI, I tried with [`^1.6`](https://travis-ci.org/github/jonom/silverstripe-focuspoint/jobs/685743549) and [`1.6.x-dev`](https://travis-ci.org/github/jonom/silverstripe-focuspoint/jobs/685760576) and both failed.

**Comment by jonom** [comment]
Maybe it should just be `dev-master`?

**Comment by maxime-rainville** [comment]
The problem was that there wasn't a minimum stability define in focus-point's `composer.json`. So it implicitly defaulted to `stable`. I've tweak it to say that `dev` dependencies are allowed. This should allow the travis build to install the dev branches.

Note that this change won't make any difference for people installing focus point on their project. Composer only honours the minimum stability of the root composer.json file.

The build is still failing but those failures were pre-existing. I got these errors while I was developing #78 and running the test locally.

**Comment by jonom** [comment]
Perfect, that did the trick. Thanks for your help. Yes there was an existing build failure, going to revert the cause of that and then we'll be green again.

**Pull request merged**
