### PR TITLE
Add support for Silverstripe 5

### PR DESCRIPTION
**Pull request by chrispenny**
## Github actions

Use Silverstripe's testing recipe and Github actions (now that Travis is not free for open source).

Action process can be seen here:
https://github.com/silverstripeltd/silverstripe-focuspoint/actions/runs/4166666330

## Potential dependency (resolved)

There was a regression in Silverstripe 5 which the team looked in to, and resolved as part of `5.0.0-beta3`:
https://github.com/silverstripe/silverstripe-framework/issues/10684

This did also require a small code change on our part (see the changes in `FocusPointDBFileExtension`).

## Composer dependencies

Update PHP minimum to `^8.1` (the same as Silverstripe 5).
Require asset admin `^2` (Silverstripe 5).

## Testing

* Asset `Focus Point` field being set and preserved
* Tried some basic usages on the frontend:
  * `$FocusFill`
  * `$FocusFillMax`
  * `$FocusCropWidth`
  * `$FocusCropHeight`
* Tried method chaining (EG):
  * `$Image.FocusCropHeight(200).FocusCropWidth(500)`

### CODE REVIEW

**Comment by jonom** [comment]
Stoked to see you're working on this, thanks @chrispenny :)

**Comment by chrispenny** [comment]
Hi @jonom, I believe this is ready for review :)

The CMS squad has made some updates in framework `5.0.0-beta3`, which has enabled us to fix the regression we were seeing with method chaining.

**Comment by jonom** [comment]
Thanks so much for this @chrispenny! I've tested quite a bit and looks like it is working well. In fact it works better than before in SS5 as [this issue](https://github.com/jonom/silverstripe-focuspoint/issues/100) seems to be resolved 😃

Do you recommend a particular release/tag here since SS5 isn't stable yet?

**Comment by jonom** [comment]
One thing - there are a bunch of [deprecation warnings](https://github.com/jonom/silverstripe-focuspoint/actions/runs/4288012979) on the tests, is that something that would be fixed upstream?

**Comment by chrispenny** [comment]
Thanks, @jonom!!! Much appreciated!

I believe the deprecation warnings would be addressed upstream (in `recipe-testing`) when required.

If you'd like to be safe, it might make sense to tag this as `5.0.0-beta1`. I've personally been tagging my modules without `beta`, and I kind of regret that - as there is a non-zero chance that API changes could still come through for Silverstripe 5.

I think it would also be good if we can please get a `4` branch, and we can use that for continued Silverstripe 4 support 😄

**Comment by jonom** [comment]
[Done](https://github.com/jonom/silverstripe-focuspoint/releases/tag/5.0.0-beta1) and [done](https://github.com/jonom/silverstripe-focuspoint/tree/4)

**Pull request merged**
