### PR TITLE
Avoid triggering exceptions in ImageManipulation by checking the imag…

### PR DESCRIPTION
**Pull request by mikenz**
…e exists and has size

### CODE REVIEW

**Comment by jonom** [comment]
Thanks for this. Does this throw a fatal error currently (before this change)? Maybe we should throw a warning instead so it doesn't just fail silently?

**Comment by mikenz** [comment]
Currently throws:
[Emergency] Uncaught InvalidArgumentException: Width is required
GET /
Line 1017 in /opt/www/backend/vendor/silverstripe/assets/src/ImageManipulation.php

In response to:
JonoM\FocusPoint\FieldType\DBFocusPoint->FocusFill(0, 0, SilverStripe\Assets\Image, )
FocusPointImageExtension.php:106


Standard FillMax(): 
https://github.com/silverstripe/silverstripe-assets/blob/master/src/ImageManipulation.php#L554

**Comment by jonom** [comment]
Alright, thanks for clarifying.

**Comment by jonom** [comment]
Tagged as 3.1.1

**Pull request merged**
