### PR TITLE
Reduce filesystem reads where possible (closes #64)

### LINKED ISSUE #64: Unnecessary filesystem reads for images
https://github.com/jonom/silverstripe-focuspoint/blob/09ae334655b0156c91aab0ceb2f2de13a7063d4f/src/FieldType/DBFocusPoint.php#L197-L222

Putting all of this _outside_ of the `$image->manipulateImage(function() { ...` closure means that even if the resampled copy exists already, focuspoint will still check the dimensions of the image. The `getWidth()`/`getHeight()` calls can result in expensive operations - intervention loads the entire image into memory to check the dimensions.

The saving grace here is that the dimensions are cached by SilverStripe once they’ve first been discovered, but if that cache is lost (e.g. after a `dev/build` or a deploy) then focuspoint will trigger re-loading the image into memory to check dimensions even when the resampled copy already exists. Even when the cached dimensions do exist, this adds unnecessary cache reads to each page load.

I had a quick look at refactoring this to move the `getWidth()`/`getHeight()` calls _inside_ the `manipulateImage()` closure. However the width/height are passed to `calculateCrop()`, and the resulting crop data is then used in the variant name. The only way I can spot to fix this would be to adjust the variant name to not use crop data - I _think_ using the requested dimensions and focuspoint x/y co-ordinates should be enough to guarantee uniqueness though...

### PR DESCRIPTION
**Pull request by kinglozzer**
Closes https://github.com/jonom/silverstripe-focuspoint/issues/64

### CODE REVIEW

**Comment by jonom** [comment]
Thanks Loz!

**Comment by jonom** [comment]
Hmm I got a broken test. My tests seem to run after merging 😅 clearly not experienced with Travis. https://travis-ci.org/jonom/silverstripe-focuspoint/builds/624827347

**Comment by jonom** [comment]
@kinglozzer I might have to revert this. The focuspoint coordinates are supposed to be adjusted after cropping so that the focuspoint sits on the same part of the image as it did before. The use case for this is that you can use the focus point in the front-end (e.g. to position a background image on a container with a different aspect ratio). I played around for a bit to try and restore this functionality but haven't had any luck. I'm a bit rusty on image manipulations now!

**Comment by kinglozzer** [comment]
Oh poo... I’ll have a think about how to fix that 😅

**Comment by tractorcow** [comment]
I've run into this issue, and I need a fix, so I'll pick up where you left off @kinglozzer :D

**Comment by tractorcow** [comment]
I did a brief review; I can see the issue in the code and have an idea for how more appropriately to resolve them. :)

**Pull request merged**
