### PR TITLE
Update FocusPointField.css

### PR DESCRIPTION
**Pull request by hdpero**
Update only current browser vendor prefixes for transition property.

### CODE REVIEW

**Comment by jonom** [comment]
@hdpero what are you considering current here? Is there any drawback to leaving those old prefixes in there?

**Comment by hdpero** [comment]
@jonom no drawbacks, but a cleaner and up-to date code...  -moz and -o vendor prefixes for older Firefox and Opera which currently have small percentage usage in world, that is why is updated.

**Comment by jonom** [comment]
Okay, fair enough. Can you just replace the space indentation with tabs please and I'll merge. Probably my fault, think I had someone else's .editorconfig in the project previously.

**Comment by hdpero** [comment]
I see that those CSS files are indented with tabs.

**Pull request closed without merging**
