### PR TITLE
Fix resampling performance issues

### LINKED ISSUE #64: Unnecessary filesystem reads for images
https://github.com/jonom/silverstripe-focuspoint/blob/09ae334655b0156c91aab0ceb2f2de13a7063d4f/src/FieldType/DBFocusPoint.php#L197-L222

Putting all of this _outside_ of the `$image->manipulateImage(function() { ...` closure means that even if the resampled copy exists already, focuspoint will still check the dimensions of the image. The `getWidth()`/`getHeight()` calls can result in expensive operations - intervention loads the entire image into memory to check the dimensions.

The saving grace here is that the dimensions are cached by SilverStripe once they’ve first been discovered, but if that cache is lost (e.g. after a `dev/build` or a deploy) then focuspoint will trigger re-loading the image into memory to check dimensions even when the resampled copy already exists. Even when the cached dimensions do exist, this adds unnecessary cache reads to each page load.

I had a quick look at refactoring this to move the `getWidth()`/`getHeight()` calls _inside_ the `manipulateImage()` closure. However the width/height are passed to `calculateCrop()`, and the resulting crop data is then used in the variant name. The only way I can spot to fix this would be to adjust the variant name to not use crop data - I _think_ using the requested dimensions and focuspoint x/y co-ordinates should be enough to guarantee uniqueness though...

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #64

This is just going to be a breaking change, (new major version, thanks semver) because there was too much to change:

 - DBFocusPoint now STORES width / height of the image as well as X and Y. This is used only as a cache, and is flushed when the image hash is modified.
 -  I've moved all of the variant handling into the extension class to separate the duties a little.
 - DBFocusPoint has lost FocusFill method, and now has an "applyCrop" that applies a $cropData array to an Image_Backend.
 - I've cleaned up / consolidated logic a little. calculateCrop now does a little more than it used to, for the sake of consolidating a bunch of logic around resampling etc...
 - bump up minimum PHP version to 7.2
 - Added a helper task to hydrate the new width / height fields (run once to speed up an old site)
 - I've split this extension into two classes, so that DBFile did not have any dataobject-specific code attached to it.
 - yarn update so you can close all those damn https://github.com/jonom/silverstripe-focuspoint/pulls :P

Todo: 
 - fix and update tests
 - compare crop method before / after change to make sure that crop focus still works

I have tested this in my site by ensuring that getImageBackend() threw an exception if called :) Seems to work ok!

### CODE REVIEW

**Comment by jonom** [comment]
> yarn update so you can close all those damn https://github.com/jonom/silverstripe-focuspoint/pulls :P

Lol THANK YOU

Now why aren't my darn tests running? Sigh *Traaaaavis*

**Comment by jonom** [comment]
Apparently they are still running but the result doesn't show up here anymore. https://travis-ci.org/github/jonom/silverstripe-focuspoint

**Comment by jonom** [comment]
Stoked that you're working on this @tractorcow. Let me know when you want me to review but I assume you want to push up some more commits first. This little snippet may come in handy to check that the focus point is updated (set focus points in different spots on the corresponding images first):

```
<% loop $List(\SilverStripe\Assets\Image).Sort('Created ASC').Limit(3) %>

    <h3>$Title</h3>

    <h4>Original focus point</h4>
    $ScaleHeight(300).DebugFocusPoint

    <h4>Updated focus point</h4>
    $FocusFill(300,100).FocusCropWidth(50).DebugFocusPoint

<% end_loop %>
```

**Comment by tractorcow** [comment]
Proof the tests work locally:

will patch up travis

image

**Comment by tractorcow** [comment]
> Stoked that you're working on this @tractorcow. Let me know when you want me to review but I assume you want to push up some more commits first. This little snippet may come in handy to check that the focus point is updated (set focus points in different spots on the corresponding images first):

I made sure to test visually too; Nothing beats a good old human acceptance test :)

**Comment by tractorcow** [comment]
Ok let's see if this travis.yml fixes the build.

**Comment by tractorcow** [comment]
Well, there are no failed builds.

But no builds at all running now. Oops!

**Comment by tractorcow** [comment]
image

**Comment by tractorcow** [comment]
@jonom please review :D

**Comment by tractorcow** [comment]
@jonom can you please put this onto a new major version as well? I suggest 4.0.0

**Comment by jonom** [comment]
Woohoo! I will review this as soon as I can, but it might take a couple of days. @kinglozzer @purplespider if you have a moment, would you be able to try out this branch as well? Hopefully it will solve the perf issues you were facing.

**Comment by tractorcow** [comment]
I ran into a few issues testing this on a site. Looks like my asserts were hit (0 width / height)

image

**Comment by tractorcow** [comment]
I think that's my own fault though :) the code just reveals the bug instead of silently failing hehe.

**Comment by tractorcow** [comment]
Ok, I have done a bunch of testing on my site, and I think I'm happy with it now.

I simplified the variant name since the full base64 encoded float ended up very long.

**Comment by jonom** [comment]
Thanks so much for working on this @tractorcow. I've tried it now and have some feedback:

1. When I tried this I immediately hit errors from `FocusCropWidth()` and `FocusCropHeight()` complaining e.g. `Trying to get property 'Height' of non-object`, which originated from the first line in those methods (the "Don't upscale" check). So might need an additional check there and perhaps return null if `$this->owner->FocusPoint` isn't a thing.
2. Not a deal breaker, but I noticed that the `FocusPointWidth` and `FocusPointHeight` only get set when you save the image. So this may not be a drop-in performance improvement for existing/published images if the perf benefit comes from those values being cached? I tried deleting all my resampled images and regenerating to be sure, and can confirm they're only updated on save.
3. The focus points are passing through to the images which are manipulated by FocusPoint, and are updated on the way, which is great! But they no longer seem to be available to the results of other manipulations.
4. [Method chaining](https://github.com/jonom/silverstripe-focuspoint/blob/master/docs/en/advanced-usage.md#method-chaining) doesn't seem to be working anymore. (Looks like I need more unit tests!)

**Example:**
```
<h2>FocusPoint tests</h2>
<% loop $List(\SilverStripe\Assets\Image).Sort('Created ASC').Limit(3) %>

    <h3>$Title (ID: $ID)</h3>

    <h4>Original focus point</h4>
    $ScaleHeight(300).DebugFocusPoint

    <h4>FP updated focus point</h4>
    $FocusFill(300,100).FocusCropWidth(50).DebugFocusPoint

    <h4>Regular updated focus point</h4>
    $ScaleHeight(200).FocusCropWidth(200).DebugFocusPoint

<% end_loop %>
```

**Before:**
Screen Shot 2021-02-20 at 11 54 50 am

**After:**
Screen Shot 2021-02-20 at 11 54 09 am

**Comment by tractorcow** [comment]
It looks like focus point isn't being set after resize,

I did notice this  bug, but I fixed it in a recent patch. Did you test a version before I pushed my patch?

The fix in question is in FocusPointDBFileExtension, and adds a getter / setter for focus point (since there's no dbield on dbfile).

**Comment by tractorcow** [comment]
> Not a deal breaker, but I noticed that the FocusPointWidth and FocusPointHeight only get set when you save the image. So this may not be a drop-in performance improvement for existing/published images if the perf benefit comes from those values being cached? I tried deleting all my resampled images and regenerating to be sure, and can confirm they're only updated on save.

I added a build task to hydrate these fields.

If you don't set the fields, the ->FocusPoint->Width etc still works, but it falls back to the old (slow) methods.

**Comment by tractorcow** [comment]
Oh, the bug is that ScaleHeight isn't a focus point resize; That's why the focus point gets lost after.

Is there anything we can / should do about that @jonom ?

**Comment by tractorcow** [comment]
@jonom I fixed it. :)

A added an override specific to DBFile extension; It inspects the failover to copy the focus point across.

**Comment by tractorcow** [comment]
Tests run fine locally.

Can confirm that the above change does not require any additional ImageBackend loads.

**Comment by tractorcow** [comment]
I think that the hydration task could use a bit more work; But the main extensions seems ready to go.

**Comment by tractorcow** [comment]
Publishing images was a bit slow; The last commit should speed it up a bit.

**Comment by jonom** [comment]
@tractorcow just a quick not to say sorry for the radio silence! Every minute of the day is tied up at the moment lol. I hope to review this on Friday.

**Comment by tractorcow** [comment]
No that's ok.

If I don't have time for a PR it can sometimes languish for years. It's not gonna stop me using this in my project. :)

I've already deployed it to 3 live websites and it's working fine (and performing well).

The only trouble I had was the hydration;

**Comment by lerni** [comment]
With thousands of images, hydration task really takes some time and eats quite a bit of disk space too but after that, it works great.

**Comment by kinglozzer** [comment]
Stress-tested this on a site which a client had killed by uploading over 300 images to a single page (most over 10mb), it solved the problem, made the page in question much faster to load, and I’m pretty sure it’s made my hair grow thicker too. 10/10 would yolo into production again.

Had the same slight issues with the hydration task taking a while, but given it’s a one-off I think it’s fine as it is now.

:shipit: 🚀

**Comment by jonom** [comment]
Apologies again for the delay on this. I spent a couple of hours testing a while back and had some problems with image chaining etc. which I mostly sorted out with some additional commits, but I need to find some time to look at this again before I can merge. Thanks for testing @kinglozzer! Enjoy that thick hair! 💇‍♂️

**Comment by tractorcow** [comment]
hi @jonom what did you need to fix? I can check for you.

**Comment by jonom** [comment]
@tractorcow I finally looked at this again! Some of the issues I experienced were either imaginary or fixed by SS4.8 as it went pretty smoothly for me this time around. I tweaked a couple of things and added some docs and have shipped [4.0](https://github.com/jonom/silverstripe-focuspoint/releases/tag/4.0.0). Thanks so much for your work on this, and @kinglozzer for the initial effort on this issue as well. 👏

**Comment by tractorcow** [comment]
oh thanks.

**Pull request merged**
